tests.yml: update 'Count bottles' step
To use new GitHub's `$GITHUB_OUTPUT` file for passing info between steps

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -43,6 +43,7 @@ jobs:
     env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
+
     steps:
       - name: Install xvfb
         run: |
@@ -96,7 +97,6 @@ jobs:
           step_name: '`brew bottle` output'
           collapse: 'true'
 
-
       - name: Upload logs
         if: always()
         uses: actions/upload-artifact@main
@@ -114,13 +114,15 @@ jobs:
         id: bottles
         if: always()
         run: |
+          shopt -s nullglob
           cd ~/bottles
-          count=$(ls *.json | wc -l | xargs echo -n)
-          echo "$count bottles"
-          echo "::set-output name=count::$count"
-          failures=$(ls failed/*.json | wc -l | xargs echo -n)
-          echo "$failures failed bottles"
-          echo "::set-output name=failures::$failures"
+          count=$(printf '%s\n' *.json | { grep -cve ^$ || true; })
+          failures=$(printf '%s\n' failed/*.json | { grep -cve ^$ || true; })
+          echo $count bottles
+          echo $failures failed bottles
+          sudo chown $(id -un) $GITHUB_OUTPUT
+          echo count=$count >> $GITHUB_OUTPUT
+          echo failures=$failures >> $GITHUB_OUTPUT
 
       - name: Upload failed bottles
         if: always() && steps.bottles.outputs.failures > 0
